version: '3'

services:
  sqlserver:
    container_name: trybe-hotel-db
    image: mcr.microsoft.com/azure-sql-edge:latest
    ports:
        - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=TrybeHotel12!
      - MSSQL_PID=Developer

      
